#!/bin/bash
rm output.html
for skin in 363511 382540; do
	cat urls | while read x
		do DIR=`dirname $x`
		mkdir -p $skin/$DIR
		wget -O $skin/$x http://prodcdngame.lordofultima.com/cdn/$skin/resource/webfrontend/$x
		echo $x'<br><img src="'$skin/$x'"><br>' >> output.html
	done
done
